version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

# Commands:
# docker-compose build
# docker-compose run --rm app sh -c "flask8"
# docker-compose run --rm app sh -c "python manage.py test"
# docker-compose run --rm app sh -c "django-admin startproject app ."
# docker-compose up